sudo: false

language: node_js

node_js:
  - node

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

scripts:
  - yarn run lint:js
  - yarn run test
  - yarn run build
  - yarn run export

deploy:
  provider: netlify
  site: $NETLIFY_ACCESS_TOKEN
  auth: $NETLIFY_SITE_ID
  edge: true # opt in to dpl v2
  dir: "out"
  on:
    branch: master

